auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  grpc_server_max_recv_msg_size: 8388608  # 8MB
  grpc_server_max_send_msg_size: 8388608  # 8MB

common:
  path_prefix: /loki
  storage:
    s3:
      endpoint: minio:9000
      bucketnames: loki-chunks
      access_key_id: ${MINIO_ACCESS_KEY_ID}
      secret_access_key: ${MINIO_SECRET_ACCESS_KEY}
      insecure: true
      s3forcepathstyle: true
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

memberlist:
  join_members: []

query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
  aws:
    endpoint: minio:9000
    bucketnames: loki-chunks
    access_key_id: ${MINIO_ACCESS_KEY_ID}
    secret_access_key: ${MINIO_SECRET_ACCESS_KEY}
    insecure: true
    s3forcepathstyle: true
    region: us-east-1

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  per_stream_rate_limit: 5MB
  per_stream_rate_limit_burst: 20MB
  max_query_parallelism: 32
  max_global_streams_per_user: 10000
  max_chunks_per_query: 2000000
  max_query_length: 721h  # 30 days
  max_query_series: 5000
  max_entries_limit_per_query: 10000
  retention_period: 168h  # 7 days - match MinIO lifecycle policy
  allow_structured_metadata: true

ingester:
  wal:
    enabled: true
    dir: /loki/wal
    flush_on_shutdown: true
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_chunk_age: 1h
  chunk_target_size: 1572864  # 1.5MB
  chunk_encoding: snappy

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150
  delete_request_store: s3

ruler:
  storage:
    type: s3
    s3:
      endpoint: minio:9000
      bucketnames: loki-ruler
      access_key_id: ${MINIO_ACCESS_KEY_ID}
      secret_access_key: ${MINIO_SECRET_ACCESS_KEY}
      insecure: true
      s3forcepathstyle: true
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true
  wal:
    dir: /loki/ruler-wal

analytics:
  reporting_enabled: false

