[api]
enabled = true

[sources.nats]
type = "nats"
url = "nats://nats:4222"
connection_name = "vector-collector"  # unique name for this connection
subject = "logs"

[sinks.loki]
type = "loki"
inputs = ["nats"]
endpoint = "http://loki:3100"
encoding.codec = "json"
labels.source = "vector"

